language: python
# 3.7 on hasta and 3.6 on thalamus
python:
  - "3.7"
  - "3.6"

services:
  - mysql

# command to install dependencies
# pip locked to version in P_main
install:
  - pip install pip==18.1
  - pip install -U -r requirements.txt .
# command to run tests
script:
  - py.test tests/ -vv --sqlalchemy-connect-url mysql+pymysql://travis@127.0.0.1/cgstats_test
  - pytest

cache: pip

jobs:
  include:
    - name: "production dependencies"
      if: type = pull_request
      script:
        - pip check
    - name: "development dependencies"
      if: type = pull_request
      script:
        - pip install -U -r requirements-dev.txt .
        - pip check
    - name: "coverage"
      if: NOT type = pull_request
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements-dev.txt
        - coverage run --branch --omit="*.html" --source "$(basename "$PWD")" setup.py test
        - coveralls
    - name: "code formatting"
      if: type = pull_request
      script:
        - pip install --upgrade pip
        - pip install black
        - git --no-pager diff --name-only --diff-filter=AM $TRAVIS_COMMIT_RANGE | grep -F ".py" | xargs black --check
    - name: "linting"
      if: type = pull_request
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements-dev.txt
        - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

notifications:
  email: never

deploy:
  provider: pypi
  user: kenny.billiau
  password:
    secure: owj2vVa/KZyBtkRZsYWcsYTXwyzCZQfGA3LWuuhpxR8CZQNOxWFfCw2fN2QJSXwGKQ6EVUdbMVoNADMcPYJgchnUMaV3o8rYlTicqgR4L/+3PN183+JBAAaqOPtiKzxYXf92RQtU/BN99WU6eg21ZLc/+w9ownVy7iD86vs1agDb8p9Y+gUke2iv9FQMTtvWShWtxQFwjUwmERYPn30F5gK8gm4Xc1No2tAiXFPS4bktsy3+0KNOUz8hxZ/c4s00fUsVesN/VG3fov9ygZwJPxfAqGdaJryg2QMXux+C1EAOc0rOB7CUBiO6dF6e15lwnE19EEu8q3bo1O/cIUd8fDtwed/nJ+Fiun9HICwaQEuh5KOOSPD1KtnZM7RQ+1ziFlS+gsQE3szhCnC/W570reODjgISiognmUxeLUn/kZgcJquX8Afnc6l+lDyj45RXHF9I1kiof3qmF3JWj5MkL2nAkl1uBPc1Rjiwt+JBDgfj9wBvImwkPh3zNwIiD7uBcBPlRgEtZM91nlL2HniYwMimE88mfEs5GcLy7pJZSOfSZxRpaZFt5gBhEqWIRYRW+KpV3zuvQrzs/bkTDFk8h+noYWYToR2fLts0x1J+kGzOmPVW7dKzSQTJlDYzvEJYhVIWmULCckQz1WLsMf2TBjuxqru3XdLD4h3ZrSOa1Jc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Clinical-Genomics/cgstats
