language: python
python:
    - "2.7"
    - "3.6"
services:
    - mysql

script:
    - py.test tests/ -vv --sqlalchemy-connect-url mysql+pymysql://travis@127.0.0.1/cgstats_test

install:
    - pip install -r requirements.txt -e .

notification:
    - email: false
