"""current models

Revision ID: 0da5c0952076
Revises: eca00ca616a6
Create Date: 2016-09-20 15:48:36.919879

"""

# revision identifiers, used by Alembic.
revision = '0da5c0952076'
down_revision = 'eca00ca616a6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from clinstatsdb.db.models import Backup

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    # UPDATE csdb.backup
    # SET backuptape_id=31
    # WHERE backuptape_id IS NULL;

    op.alter_column('backup', 'backuptape_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('flowcell', 'hiseqtype',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text(u"'hiseqga'"))
    op.alter_column('project', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('unaligned', 'demux_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('unaligned', 'sample_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('unaligned', 'approved')
    op.create_unique_constraint('name_major_minor_patch_uc', 'version', ['name', 'major', 'minor', 'patch'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_major_minor_patch_uc', 'version', type_='unique')
    op.add_column('unaligned', sa.Column('approved', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True))
    op.alter_column('unaligned', 'sample_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('unaligned', 'demux_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('project', 'time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('flowcell', 'hiseqtype',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text(u"'hiseqga'"))
    op.alter_column('backup', 'backuptape_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
