"""add post alignment tables

Revision ID: a0e7145e6e45
Revises: 0da5c0952076
Create Date: 2016-09-20 16:33:17.040729

"""

# revision identifiers, used by Alembic.
revision = 'a0e7145e6e45'
down_revision = '0da5c0952076'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline', sa.String(length=32), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('_program_versions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('analysis_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.String(length=32), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('sequencing_type', sa.Enum('wes', 'wgs'), nullable=True),
    sa.Column('sex_predicted', sa.Enum('male', 'female', 'unknown'), nullable=True),
    sa.Column('capture_kit', sa.String(length=32), nullable=True),
    sa.Column('library_kit_lot_1', sa.String(length=32), nullable=True),
    sa.Column('library_kit_lot_2', sa.String(length=32), nullable=True),
    sa.Column('baits_lot', sa.String(length=64), nullable=True),
    sa.Column('beads_t1_lot', sa.String(length=32), nullable=True),
    sa.Column('fragment_size', sa.Integer(), nullable=True),
    sa.Column('dna_concentration', sa.Float(), nullable=True),
    sa.Column('input_material', sa.Float(), nullable=True),
    sa.Column('index_sequence', sa.String(length=32), nullable=True),
    sa.Column('reads_total', sa.Integer(), nullable=True),
    sa.Column('mapped_percent', sa.Float(), nullable=True),
    sa.Column('duplicates_percent', sa.Float(), nullable=True),
    sa.Column('strand_balance', sa.Float(), nullable=True),
    sa.Column('coverage_target', sa.Float(), nullable=True),
    sa.Column('completeness_target_10', sa.Float(), nullable=True),
    sa.Column('completeness_target_20', sa.Float(), nullable=True),
    sa.Column('completeness_target_50', sa.Float(), nullable=True),
    sa.Column('completeness_target_100', sa.Float(), nullable=True),
    sa.Column('variants', sa.Integer(), nullable=True),
    sa.Column('indels', sa.Integer(), nullable=True),
    sa.Column('snps', sa.Integer(), nullable=True),
    sa.Column('novel_sites', sa.Integer(), nullable=True),
    sa.Column('concordant_rate', sa.Float(), nullable=True),
    sa.Column('hethom_ratio', sa.Float(), nullable=True),
    sa.Column('titv_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('sample_flowcell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flowcell_id', sa.String(length=16), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('cbot_machine', sa.String(length=32), nullable=True),
    sa.Column('sequencing_machine', sa.String(length=32), nullable=True),
    sa.Column('run_mode', sa.String(length=32), nullable=True),
    sa.Column('sequencing_reagents_1', sa.String(length=32), nullable=True),
    sa.Column('sequencing_reagents_2', sa.String(length=32), nullable=True),
    sa.Column('sequencing_cluster_1', sa.String(length=32), nullable=True),
    sa.Column('sequencing_cluster_2', sa.String(length=32), nullable=True),
    sa.Column('cluster_concentration', sa.Float(), nullable=True),
    sa.Column('q30', sa.Float(), nullable=True),
    sa.Column('reads', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['analysis_sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_flowcell')
    op.drop_table('analysis_sample')
    op.drop_table('analysis')
    ### end Alembic commands ###
