"""current structure

Revision ID: eca00ca616a6
Revises: 
Create Date: 2016-09-20 15:06:39.370122

"""

# revision identifiers, used by Alembic.
revision = 'eca00ca616a6'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
